// <auto-generated />
namespace PT.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class iki : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iki));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281235172_iki"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
