// <auto-generated />
namespace PT.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ilk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ilk));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281202232_ilk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
